### ISSUE TITLE
확장자 추가

### ISSUE THREAD

**Issue by marshallku** [young-sinf/express-board-app#1]
https://github.com/younGsse/express-board-app/blob/a45f6c3e81598026ecccadad794e1ef2577b357e/app.js#L7

https://github.com/younGsse/express-board-app/blob/a45f6c3e81598026ecccadad794e1ef2577b357e/routes/api/post.js#L2-L4

확장자(`.js`)가 생략되어 있습니다.

`import` 스펙에서 [Mandatory File Extensions](https://nodejs.org/api/esm.html#mandatory-file-extensions)를 참고해보시면, 디렉터리 index 파일을 불러올 때를 포함해 항상 확장자까지 모두 명시하라고 되어 있습니다.

**Comment by 0sinf** [comment]
테스트에서 에러 없어 동작하기에 문제 없는 줄 알았습니다.
테스트 환경에서는 어떻게 돌아가는지 확인해봐야겠네요!
