### ISSUE TITLE
의존성 누락

### ISSUE THREAD

**Issue by marshallku** [young-sinf/express-board-app#2]
https://github.com/younGsse/express-board-app/blob/a45f6c3e81598026ecccadad794e1ef2577b357e/package.json#L9

https://github.com/younGsse/express-board-app/blob/a45f6c3e81598026ecccadad794e1ef2577b357e/package.json#L12-L30

`start` 스크립트에서 `nodemon`을 사용하나, `nodemon`에 대한 의존성이 추가되어있지 않습니다.

**Comment by 0sinf** [comment]
글로벌로 설치 되어있어 확인하지 못했습니다.
의존성 추가 했습니다 😅
